
-- 1. BRANCH
CREATE TABLE BRANCH (
    BRANCH_ID VARCHAR2(10) PRIMARY KEY,
    BRANCH_NAME VARCHAR2(100),
    ADDRESS VARCHAR2(255)
);

-- 2. EMPLOYEE
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID VARCHAR2(10) PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    PHONE VARCHAR2(20),
    JOIN_DATE DATE,
    SALARY NUMBER(12, 2),
    BRANCH_ID VARCHAR2(10),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(BRANCH_ID)
);

-- 3. CUSTOMER
CREATE TABLE CUSTOMER (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    PHONE VARCHAR2(20),
    REGISTRATION_DATE DATE
);

-- 4. INVOICE
CREATE TABLE INVOICE (
    INVOICE_ID VARCHAR2(20) PRIMARY KEY,
    INVOICE_DATE DATE,
    TOTAL_AMOUNT NUMBER(15, 2),
    EMPLOYEE_ID VARCHAR2(10),
    CUSTOMER_ID NUMBER,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

-- 5. INVOICE_DETAIL
CREATE TABLE INVOICE_DETAIL (
    INVOICE_ID VARCHAR2(20),
    PRODUCT_ID VARCHAR2(20),
    QUANTITY NUMBER,
    PRIMARY KEY (INVOICE_ID, PRODUCT_ID),
    FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE(INVOICE_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

-- 6. PRODUCT
CREATE TABLE PRODUCT (
    PRODUCT_ID VARCHAR2(20) PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(100),
    UNIT_PRICE NUMBER(12, 2)
);

-- 7. PRODUCT_STOCK_EMPLOYEE
CREATE TABLE PRODUCT_STOCK_EMPLOYEE (
    BRANCH_ID VARCHAR2(10),
    PRODUCT_ID VARCHAR2(20),
    STATUS VARCHAR2(20),
    PRIMARY KEY (BRANCH_ID, PRODUCT_ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(BRANCH_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

-- 8. PRODUCT_STOCK_MANAGER
CREATE TABLE PRODUCT_STOCK_MANAGER (
    BRANCH_ID VARCHAR2(10),
    PRODUCT_ID VARCHAR2(20),
    QUANTITY_IN_STOCK NUMBER,
    LAST_UPDATE_DATE DATE,
    PRIMARY KEY (BRANCH_ID, PRODUCT_ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(BRANCH_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);
